import React from 'react';
import SignUpForm from '@/app/comps/signupForm';
import Link from 'next/link';

export const metadata = {
    title: "Saturn | Sign Up",
    description: "Generated by create next app",
  };

const Signup = () => {
    return (
        <main key={Signup} className=' bg-[#f5f5f5] flex flex-col items-center'>
            <div className='flex flex-col items-center'>
                <div className='flex flex-col items-center'>
                    <h1 className='text-center text-blue-600 text-4xl font-bold mb-4 lg:text-6xl'>Sign up to Saturn</ h1>
                    <p className='max-w-[1000px] text-center lg-text-2xl xl:text-3xl lg:font-semibold'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita sint blanditiis, enim voluptatibus vitae ipsa eius ad.</p>
                </ div>

                <SignUpForm />
            </ div>
            <aside className='w-full bg-white p-5 lg:px-20 mt-6'>
                <ul className='flex items-center gap-x-3'>
                    <li className='text-2xl font-bold'><Link href='/'>Saturn</Link></li>
                    <li className='text-2xl'>&gt;</li>
                    <li className='text-2xl text-slate-500'>Signup</li>
                </ul>
            </aside>
        </main>
    );
}

export default Signup;